collections:
  n:
    permalink: /n/:path
    output: true
  b:
    permalink: /b/:path
    output: true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               MiPais
tagline:             'Datos, análisis, programas'
description:         ''
url:                 'https://mipais.github.io'
#baseurl:             'https://mipais.github.io'
paginate:            5

# About/contact
author:
  name:              MiPais
  url:               https://mipais.github.io
  email:             

# Custom vars
version:             2.0.0

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "n"
    values:
      layout: "news"
      imgdir: "nimg"
      imgtype: ".png"
  -
    scope:
      path: "b"
    values:
      layout: "burns"
      imgdir: "bimg"
      imgtype: ".jpg"
  -
    scope:
      path: ""
      type: ""
    values:
      layout: "page"
      imgdir: "XXXERROR"
      imgtype: ".jpg"
